version: "3.9"
services:
  nextjs:
    image: promptrun:latest
    container_name: promptrun
    ports:
      - "3000:3000"
    restart: always
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # 证书文件放置在 /etc/ssl 目录下，挂在到容器的 /etc/nginx/ssl 目录下
      - /etc/ssl:/etc/nginx/ssl:ro
    restart: always
